// GENERATED by apps/api/scripts/export_block_contract.py — do not edit.
// Single source of truth: apps/api/app/blocks.py
export const BLOCK_CONTRACT = {
  "version": 1,
  "block_types": [
    "summary",
    "key_points",
    "key_terms",
    "steps",
    "table",
    "comparison",
    "progress",
    "faq",
    "callout",
    "chips",
    "timeline",
    "metrics",
    "quote",
    "chart",
    "flow_diagram",
    "sequence_diagram"
  ],
  "source_hints": [
    "summary",
    "key_points",
    "concepts",
    "ordered_actions",
    "matrix_rows",
    "comparisons",
    "levels",
    "faq",
    "priority_message",
    "themes",
    "milestones",
    "metrics",
    "process_flow",
    "interaction_sequence"
  ],
  "widths": {
    "summary": "full",
    "key_points": "half",
    "key_terms": "promote",
    "steps": "full",
    "table": "full",
    "comparison": "full",
    "progress": "promote",
    "faq": "half",
    "callout": "half",
    "chips": "full",
    "timeline": "full",
    "metrics": "promote",
    "quote": "half",
    "chart": "full",
    "flow_diagram": "full",
    "sequence_diagram": "full"
  }
} as const;

export const KNOWN_BLOCK_TYPES: ReadonlySet<string> = new Set(
  BLOCK_CONTRACT.block_types,
);
