import type { Workspace } from "@/api";

export type SettingsPageContextValue = {
  email: string;
  error: string | null;
  savingProfile: boolean;
  savingPassword: boolean;
  currentPassword: string;
  newPassword: string;
  confirmPassword: string;
  workspaces: Workspace[];
  newWsName: string;
  creatingWs: boolean;
  editingId: string | null;
  editName: string;
  editDescription: string;
  editTags: string;
  savingEdit: boolean;
  onEmailChange: (v: string) => void;
  onUpdateProfile: () => Promise<void>;
  onCurrentPasswordChange: (v: string) => void;
  onNewPasswordChange: (v: string) => void;
  onConfirmPasswordChange: (v: string) => void;
  onChangePassword: () => Promise<void>;
  onNewWsNameChange: (v: string) => void;
  onCreateWorkspace: () => Promise<void>;
  onStartEdit: (ws: Workspace) => void;
  onEditNameChange: (v: string) => void;
  onEditDescriptionChange: (v: string) => void;
  onEditTagsChange: (v: string) => void;
  onCancelEdit: () => void;
  onSaveEdit: (id: string) => Promise<void>;
  onDeleteWorkspace: (id: string) => Promise<void>;
  onDismissError: () => void;
  onRetryError: () => void;
  onLogout: () => void;
};