"""Regenerate the web block contract from the block registry.

Run from apps/api:  uv run python scripts/export_block_contract.py
A registry test (test_block_registry.py) fails when the generated file on
disk no longer matches the registry, so drift can't merge silently.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.visual_summary.blocks.registry import web_contract  # noqa: E402

CONTRACT_PATH = (
    Path(__file__).resolve().parents[3]
    / "apps"
    / "web"
    / "src"
    / "components"
    / "agents"
    / "block-contract.ts"
)


def render_contract_ts() -> str:
    payload = json.dumps(web_contract(), indent=2)
    return (
        "// GENERATED by apps/api/scripts/export_block_contract.py — do not edit.\n"
        "// Single source of truth: apps/api/app/blocks.py\n"
        f"export const BLOCK_CONTRACT = {payload} as const;\n\n"
        "export const KNOWN_BLOCK_TYPES: ReadonlySet<string> = new Set(\n"
        "  BLOCK_CONTRACT.block_types,\n"
        ");\n"
    )


if __name__ == "__main__":
    CONTRACT_PATH.write_text(render_contract_ts())
    print(f"wrote {CONTRACT_PATH}")
